"""Add registration_date to users table

Revision ID: 0b7fd0ac237e
Revises: ffca00d45f26
Create Date: 2024-06-26 16:42:05.203368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b7fd0ac237e'
down_revision: Union[str, None] = 'ffca00d45f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reg_date', sa.DateTime(), nullable=True))
    op.drop_column('users', 'registration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'reg_date')
    # ### end Alembic commands ###
