"""Create chat_full_texts table with separate primary key and remove the full_text relate columns from Chat

Revision ID: 0e4c58ef3bc5
Revises: c95839075a9b
Create Date: 2024-07-14 13:26:56.063024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e4c58ef3bc5"
down_revision: Union[str, None] = "c95839075a9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_full_texts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.String(length=255), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("sanitized_text_presidio", sa.Text(), nullable=True),
        sa.Column("annotated_text_presidio", sa.Text(), nullable=True),
        sa.Column("sanitized_text_chatgpt", sa.Text(), nullable=True),
        sa.Column("annotated_text_chatgpt", sa.Text(), nullable=True),
        sa.Column("sanitized_text_local_llm", sa.Text(), nullable=True),
        sa.Column("annotated_text_local_llm", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Remove the full_text and sanitized_text columns from chats table, if they exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("chats")]
    if "full_text" in columns:
        op.drop_column("chats", "full_text")
    if "sanitized_text" in columns:
        op.drop_column("chats", "sanitized_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("full_text", sa.Text(), nullable=True))
    op.add_column("chats", sa.Column("sanitized_text", sa.Text(), nullable=True))

    op.drop_table("chat_full_texts")
    # ### end Alembic commands ###
