"""Add lead_name column to Chat

Revision ID: 151753512221
Revises: e6ffb480e843
Create Date: 2024-06-23 22:25:10.882433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151753512221'
down_revision: Union[str, None] = 'e6ffb480e843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('lead_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    op.drop_column('chats', 'lead_name')
    # ### end Alembic commands ###
