"""Add phone_code_hash to Session table

Revision ID: 197f9181c9e0
Revises: 4a5d5a45bd8c
Create Date: 2024-06-30 22:53:53.491350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197f9181c9e0'
down_revision: Union[str, None] = '4a5d5a45bd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('phone_code_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'phone_code_hash')
    # ### end Alembic commands ###
