"""Add telegram_id and remove lead_name from Chats

Revision ID: 2aae44677238
Revises: 66f7775bea6d
Create Date: 2024-06-30 17:18:09.286647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2aae44677238"
down_revision: Union[str, None] = "66f7775bea6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats", sa.Column("telegram_id", sa.BigInteger(), nullable=True, default=0)
    )
    op.drop_column("chats", "lead_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column(
            "lead_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("chats", "telegram_id")
    # ### end Alembic commands ###
