"""Change id of Session from String to Text

Revision ID: 4a5d5a45bd8c
Revises: 6cd0b91b0b97
Create Date: 2024-06-30 22:08:31.221358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5d5a45bd8c'
down_revision: Union[str, None] = '6cd0b91b0b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions') as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.String(length=255),
                              type_=sa.Text,
                              existing_nullable=False, primary_key=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
