"""Add created_date and send_code_date to Session table

Revision ID: 6cd0b91b0b97
Revises: 92fc782c2340
Create Date: 2024-06-30 21:22:11.021603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd0b91b0b97'
down_revision: Union[str, None] = '92fc782c2340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('send_code_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'send_code_date')
    op.drop_column('sessions', 'creation_date')
    # ### end Alembic commands ###
