"""Add full_text and sanitized_text to chats

Revision ID: c95839075a9b
Revises: 7c9d3c13e582
Create Date: 2024-07-14 00:48:19.390468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c95839075a9b"
down_revision: Union[str, None] = "7c9d3c13e582"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alembic_version")
    op.add_column("chats", sa.Column("full_text", sa.Text(), nullable=True))
    op.add_column("chats", sa.Column("sanitized_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "sanitized_text")
    op.drop_column("chats", "full_text")
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("version_num", name="alembic_version_pkc"),
    )
    # ### end Alembic commands ###
