"""Add is_logged to Session table

Revision ID: f14d52888288
Revises: 197f9181c9e0
Create Date: 2024-07-01 15:21:10.780336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f14d52888288"
down_revision: Union[str, None] = "197f9181c9e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("is_logged", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "is_logged")
    # ### end Alembic commands ###
